import { HttpError } from './HttpError.js'
import type { ErrorMetadata } from '../types.js'

/**
 * 511 Network Authentication Required
 * The HTTP 511 Network Authentication Required response status code
 * indicates that the client needs to authenticate to gain network access.
 *
 * This status is not generated by origin servers,
 * but by intercepting proxies that control access to the network.
 *
 * Network operators sometimes require some authentication,
 * acceptance of terms, or other user interaction before granting access
 * (for example in an internet café or at an airport). They often identify clients
 * who have not done so using their Media Access Control (MAC) addresses.
 *
 * Source: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/511
 */
export class NetworkAuthenticationRequiredError extends HttpError {
    constructor(message = 'Network Authentication Required', metadata?: ErrorMetadata) {
        super(message, 511, metadata)
    }
}
